### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [sghillo/Tea_Cozy#5]
Grade: Meets expectations

Summary:
Awesome work on this project! I like your use of the semantic HTML element, your use of locally stored images, and your use of flex-box in CSS.

A few things to work on here would be: 1. using descriptive `alt` attributes on your `<img>` elements, 2. using relative file paths for your background images, and 3. using group selectors to make your CSS more concise.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page responsive for all screen widths.  This is a challenge I think you are ready for based on your work with this project!  Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by sghillo** [comment]
Hi Aubrey,

Thank you so much for your review. 

I will update the project with your feedback and media queries. 

Cheers, 

Dario
